### PR TITLE
Added a function for drawing a tab bar

### PR DESCRIPTION
**Pull request by unlimitedbacon**
tabs1
tabs2
tabs3

### CODE REVIEW

**Comment by Willem3141** [comment]
That looks very useful, but personally I don't think the "overlapping" tabs are a good idea. They make it harder to read what's on the tabs, and they only reduce the vertical space usage by one pixel.

Here's a mock-up:
tabbar-mockup
I also added some arrows to indicate that the user can use the arrow keys to switch to the next/previous tab, but I don't know if that is a good idea.

**Comment by SirCmpwn** [comment]
@Willem3141 this was heavily discussed and iterated over in #knightos earlier, and we settled on this design.

**Comment by Willem3141** [comment]
Ah, okay. Sorry.

**Comment by SirCmpwn** [comment]
The crux of the issue is that we need all UI elements to take up multiples of 6 pixels in height, so that we can have a consistent number of rows available for text.

**Pull request merged**
